name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install "black[jupyter]" isort flake8
      - run: black --check .
      - run: isort --check-only .
      - run: flake8
