# .github/workflows/simple.yml
name: Simple Python Workflow

on:
  push:
    branches: [ main ]   # run when code is pushed to main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run hello script
        run: python hello.py
